name: Benchmark

on:
  push:
    branches: [ main ]
    paths:
      - 'src/*'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/bench.yml'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_RELEASE_DEBUG: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure environment
      run: |
        git config --global user.name GitHub_Action
        sudo sysctl -w kernel.perf_event_paranoid=-1
    
    - name: Merge main update
      run: |
        git checkout main
        git checkout bench
        git merge --squash main

    - name: Bench
      run: |
        cargo install flamegraph
        cargo flamegraph -c "record -e instructions -c 100 -g"  -- --max=50 -n 10
    
    - name: Store result
      run: |
        git add .
        git commit -m "flamegraph"
        git push

