name: Check

on:
  push:
    branches: [ main ]
    paths:
      - 'src/*'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/check.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/bench.yml'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Test build
      run: |
        cargo build
        cargo test
    
    - name: Real test
      run: cargo run -- --max=5 -n 10

