name: Release

on:
  push:
    branches: [ main ]
    paths:
      - 'src/*'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - '.github/workflows/release.yml'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --release
    
    - name: Create release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "target/release/mirrorsite"
        draft: false
        overwrite: true
        update_latest_release: true

